In [1]:
import numpy as np

In [2]:
import pandas as pd
import joblib
from sklearn.model_selection  import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [5]:
df = pd.read_csv(r'C:\Users\harin\OneDrive\Desktop\project1.csv')

In [6]:
df.head()

Names Gender
0   Pooja      f
1   Priya      f
2  Aakash      m
3    Hari      m
4   Janvi      f

In [7]:
df.size

20

In [8]:
df.columns

Index(['Names', 'Gender'], dtype='object')

In [9]:
df.dtypes

Names     object
Gender    object
dtype: object

In [10]:
df.isnull().isnull().sum()

Names     0
Gender    0
dtype: int64

In [12]:
df[df.Gender == 'f'].size

10

In [13]:
df_names = df

In [14]:
df_names.Gender.replace({'f': 0, 'm':1}, inplace=True)

C:\Users\harin\AppData\Local\Temp\ipykernel_16964\1904973148.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_names.Gender.replace({'f': 0, 'm':1}, inplace=True)


In [15]:
df_names.head()

Names  Gender
0   Pooja       0
1   Priya       0
2  Aakash       1
3    Hari       1
4   Janvi       0

In [16]:
df_names.Gender.unique()

array([0, 1], dtype=int64)

In [17]:
df_names.dtypes

Names     object
Gender     int64
dtype: object

In [19]:
xfeatures = df_names['Names']

In [21]:
cv = CountVectorizer()
x = cv.fit_transform(xfeatures.values.astype('U'))

In [22]:
x.shape

(10, 10)

In [24]:
gender_vectorizer = open("gender_vectorizer.pkl", "wb")
joblib.dump(cv, gender_vectorizer)

In [25]:
gender_vectorizer.close()

In [26]:
cv.get_feature_names_out()

array(['aakash', 'hari', 'janani', 'janvi', 'lakshmi', 'muthu', 'pooja',
       'prakash', 'priya', 'shadhik'], dtype=object)

In [28]:
y = df_names.Gender

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [32]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.5

In [33]:
print("accuracy of model - > {} %".format(clf.score(x_test, y_test)*100))

accuracy of model - > 50.0 %


In [34]:
print("accuracy of model - > {} %".format(clf.score(x_train, y_train)*100))

accuracy of model - > 100.0 %


In [35]:
sample_names = ["Hari"]
vect = cv.transform(sample_names).toarray()
clf.predict(vect)

array([1], dtype=int64)

In [36]:
sample_names2 = ["janvi"]
vect = cv.transform(sample_names2).toarray()
clf.predict(vect)

array([0], dtype=int64)

In [38]:
sample_names3 = ['Pooja','Janani','Shadhik','Prakash','Priya','Janvi','Hari']
vect = cv.transform(sample_names3).toarray()
clf.predict(vect)

array([0, 0, 1, 1, 0, 0, 1], dtype=int64)

In [39]:
def gender_predictor(name):
    test_name = [name]
    vector = cv.transform(test_name).toarray()
    if clf.predict(vector) == 0:
        return "Female"
    else:
        return "Male"


In [40]:
for i in sample_names3:
    print(i, "->", gender_predictor(i))

Pooja -> Female
Janani -> Female
Shadhik -> Male
Prakash -> Male
Priya -> Female
Janvi -> Female
Hari -> Male


In [42]:
gender_predictor('Aakash')

'Male'